### ISSUE TITLE
Enquiry on the features of DRAMSys and DRAMPower 

### ISSUE THREAD

**Issue by Dang-Jie** [tukl-msd/DRAMSys#37]
Hello there, thank you for providing these tools. I have some questions regarding the simulation tool and would greatly appreciate any assistance you can provide. Currently, I am using DRAMSys 5.0 + DRAMPower 5.0

1) How can we determine the data at a specific address? I don't see the value of the data in the Transaction and Phases table from the generated tdb file. Is it located elsewhere? Or is it a feature of the Trace Analyzer?

2) Is VRT (Variable Retention Time) considered and implemented inside the tools?

3) Does the tool provide an ECC mechanism? If so, how can the ECC feature be enabled?

4) I noticed that there was a way to display energy values (e.g. auto refresh, self-refresh energy, etc.) in the previous version (possibly). Where can I find this information in DRAMSys? I believe that these details should already be integrated into DRAMSys.

5) Is there a way to count the number of events that have occurred, such as refreshes, reads, writes, and precharges?

6) Taking _MICRON_4Gb_DDR4-2400_8bit_A_ memspec as an example, I discovered that the value of _tREFI_ is 4680. My understanding is that _tREFI_ for 85 degrees Celsius should be 7.8 microseconds, so I am unsure what this value of 4680 represents."

7) Also, although I am not sure about the _tREFI_ value, I assume that it follows the pattern where a larger _tREFI_ corresponds to a longer refresh period. In this case, assuming the value of _tREFI_ is 4680 (equivalent to 64ms), I tried doubling the value in an attempt to reduce energy consumption during simulation. However, when I doubled it, the average power increased; and when I halved the _tREFI_ , the average power decreased.
I am using the below configs to produce results:
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/bb32bc6e-92d5-48c1-9c93-bda3ddbc7363)
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/4864f521-f0d6-45f3-b453-eb2ccd7f41de)
when i amend _tREFI_ inside _MICRON_4Gb_DDR4-2400_8bit_A_ to 2340 (original is 4680), i get:
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/6a6144ad-01fe-4698-bdd7-9d520fb73fff)
amend to 9360, i get:
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/172694cf-a1b7-4b99-bdbd-a356bc7a8de9)

8) Furthermore, I have observed that modifying the _AllBank_ or _NoRefresh_ options in the default _ddr4-example.json_ file does not affect the energy output. Additionally, when using the configuration provided below, I discovered that the average power consumption of the _NoRefresh_ policy is higher than that of the _AllBank_ refresh policy
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/ba93547b-db72-4812-98c1-a3e9c91ebe3d)
Result of _AllBank_ :
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/8d27f4ae-d1a3-4678-be1c-990e4f86c44c)
Result of _NoRefresh_ :
![image](https://github.com/tukl-msd/DRAMSys/assets/139112849/067256a1-578d-44b2-bb0e-41b410f93eca)

**Comment by lsteiner-tukl** [comment]
1. The data is not recorded in the tdb file. But you could use TLM's debug transactions to check the data during simulation with low effort.
2. This is not implemented yet. 
3. We have implemented an inline ECC mechanism. A conventional external ECC that uses an extra device on the DIMM does not influence the performance (as long as you are not doing partial writes that require a read-modify-write). You can also find some deprecated ECC-related code on tag v4.0.
4. The energy information can be accessed and displayed inside DRAMPower. Please have a look at that repository.
5. You can use SQL queries to extract this information from the generated database, e.g., "SELECT count(*) FROM Phases WHERE PhaseName = 'RD'".
6. Maybe this file assumes fine granularity refresh where tREFI is half of the normal value.
7. I think it depends on the trace. If you are running an idle simulation where no RD/WR requests are handled then more refresh commands should increase the power. However, if you are running a simulation with continuous RD/WR commands, more refresh commands mean more interruptions, and IDD5B is usually smaller than IDD4R/W.
8. Same here, without refresh the simulation is shorter and the total energy is smaller, but the average power is higher because the RD/WR commands are denser.
